Gemfile, Gemfile.lock, echo_api.rb
Unprintable characters in a chunk are skipped.
Resolves #7 and #8.
=> Return the request body size and SHA1 hash. Resolves #7 and #8.

echo_api.rb
We are removing the size and wait resources due to DOS security issues.
=> Removing the "size" and "wait" resources

Gemfile, Gemfile.lock, echo_api.rb
This adds CORS support to all routes on the echo api. It should close #19.
=> Adding CORS support

Makefile, echo_api.rb
=> Disabling Protection

openapi-spec/swagger.yaml, spec/openapi.json
=> Introducing swagger spec

openapi-spec/swagger.json, openapi-spec/swagger.yaml
* Adding proper tags to get the documetation organized in active docs
* changing the tags from Wildcard Route to Wildcard Path
* Adding the JSON swagger definition
* Removing /v1 basepath
=> Add JSON Swagger defnition file

README.md
Introducing the new Production URL for the echo-api
=> Changes the Echo Api URL on the documentation

openshift/echo-api-template.yml
Updating the Deployment Config version, to always be even with the master branch of the repo.
=> Updating docker image tag to master in the deploymentConfig

.circleci/config.yml, Gemfile
just a simple smoke test to verify it starts and works
start the server and make a request to it
=> [ci] set up circleci

openshift/README.md, openshift/echo-api-template.yml
The image is now public in quay, we don't need to add credentials to
pull it anymore.
=> Remove authorization requirement for quay registry

.circleci/config.yml
* do not daemonize rackup to show error messages
* fix caching and cache by architecture
to prevent errors like "libssl.so.1.0.0: cannot open shared object file"
=> fix Circle CI build

Gemfile, config.ru, echo_api.rb
=> [rubocop] apply --auto-correct

.circleci/config.yml, echo_api.rb
=> [opentracing] fix jaeger tracer

istio/deployment.yaml, istio/gateway.yaml, openshift/README.md
Adds required templates and instructions to integrate the api within istio service mesh
=> Istio support

Makefile
While at it also declare the phony targets.
=> Makefile: refactor image checks and use "run" target interactively

Dockerfile
You'd figure you'd want to run the app in **production** mode when in production rather than spewing out internal details to users, right?
=> Dockerfile: run the application in production in... production mode

echo_api.rb
This avoids two trivial inefficiencies: looking up headers twice and using a regexp engine for a trivial trimming operation.
=> echo_api: use minimally trivial optimisations

echo_api.rb
=> echo_api: echo back Content-length and Content-type headers if present

contrib/kubernetes/echo-api.yaml
This adds a minimal Kubernetes deployment and service.
=> contrib: add sample kubernetes manifest

.dockerignore, CHANGELOG.md, contrib/kubernetes/README.md, contrib/kubernetes/echo-api-with-jaeger.yaml, contrib/kubernetes/jaeger.yaml, echo_api.rb
Minor stuff with the important thing being the regression fix for running the image on Openshift.
=> Release 1.0.3

CHANGELOG.md, Dockerfile, Gemfile.lock, echo_api.rb
This is 1.0.4 with dependency upgrades and a ppc64le build.
=> Release 1.0.4

Dockerfile, Gemfile.lock
Update to use the newest bundler release from 2.3.
=> Bundler 2.3.4

CHANGELOG.md, Dockerfile, Gemfile.lock, echo_api.rb
Just dependency updates and an optimization of the container image.
=> Release 1.0.5

.gitignore, Dockerfile, contrib/openshift/README.md, contrib/openshift/echo-api-template.yml
Just some suggestions for https://github.com/3scale/echo-api/pull/344
=> Some suggestions
